# Aa a Aa 0.0.0 a 0-0-0 0:0N
N
a a.a a a, aN
N
N
a Aa(a.Aa):N
N
    a = [N
        ('a', '0_a'),N
    ]N
N
    a = [N
        a.AaAa(N
            a_a='a',N
            a='a_a',N
        ),N
        a.AaAa(N
            a_a='a',N
            a='a_a_a_a',N
        ),N
        a.AaAa(N
            a_a='a',N
            a='a_a',N
        ),N
        a.AaAa(N
            a_a='a',N
            a='a_a',N
        ),N
        a.AaAa(N
            a_a='a',N
            a='a_a',N
            a=a.AaAa(a=''),N
        ),N
        a.AaAa(N
            a_a='a',N
            a='a_a',N
            a=a.AaAa(a=''),N
        ),N
        a.AaAa(N
            a_a='a',N
            a='a_a',N
            a=a.AaAa(a=''),N
        ),N
        a.AaAa(N
            a_a='a',N
            a='a_a',N
            a=a.AaAa(a=''),N
        ),N
        a.AaAa(N
            a_a='a',N
            a='a_a',N
            a=a.AaAa(a=''),N
        ),N
        a.AaAa(N
            a_a='a',N
            a='a_a',N
            a=a.AaAa(a=''),N
        ),N
        a.AaAa(N
            a_a='a',N
            a='a_a',N
            a=a.AaAa(a=''),N
        ),N
        a.AaAa(N
            a_a='a',N
            a='a_a',N
            a=a.AaAa(a=''),N
        ),N
        a.AaAa(N
            a_a='a',N
            a='a_a',N
            a=a.AaAa(a=''),N
        ),N
        a.AaAa(N
            a_a='a',N
            a='a_a',N
            a=a.AaAa(a=''),N
        ),N
        a.AaAa(N
            a_a='a',N
            a='a_a',N
            a=a.AaAa(a=''),N
        ),N
        a.AaAa(N
            a_a='a',N
            a='a_a',N
            a=a.AaAa(a=''),N
        ),N
    ]N
