;N
;AaAa0			a		0a0N
;AaAa0			a		0a0N
;AaAa0			a		0a0N
;AaAa0			a		0a0N
; Aa0			a		0a0N
; Aa0			a		0a0N
; Aa0			a		0a0N
; Aa0			a		0a0N
; AaAa			a		0a0		;N
; AaAa			a		0a0N
N
; AaAa0             a     0a0N
; AaAa             a     AaAa0             ;  AaAa N
; AaAa          a     0a0                ; N
; A0Aa             a     AaAa   +   0  ;N
; AaAa             a     A0Aa      +   0  ;N
; AaAa             a     AaAa      +   0  ;N
; A                a     AaAa      +   0  ;N
; Aa                a     A         +   0  ;N
; AaAaAa          a     Aa         +   0  ;   0AN
; AaAaAa         a     AaAaAa   +   A_AaAaAa  ; A 0N
; AaAa             a     AaAaAa  +   A_AaAaAa  ;N
N
Aa0a             a     0a0N
AaAa0             a     0a0N
N
AaAa          a     AaAaN
N
AaAa            a     0a0AN
AaAaAa           a     0a0AN
AaAa0             a     0a0AN
AaAa         a     0a0AN
Aa0aAa          a     0a0AN
AaAa             a     0a0N
N
A_A              a     AaAa ;  	 +   0  ; N
A_A              a     AaAa ;     +   0  ; N
A_A             a     AaAa ;     +   0  ; N
N
N
AaAa          ==      A_A