;****************************************************N
;AaAaN
;   A.A  N
; AaA       a     0N
; AaA       a     0N
; A_Aa      a     0N
    A_AaAa     a      0N
    A_AaAaAa        a      0       ; A0A0  AN
    A_Aa         a      0N
;AaAa0   A0A0    N
    A_Aa0a       a      0N
    A_0a         a      0N
    A_0a         a      0N
;****************************************************N
    A_AaAaAa    ==    0N
N
	A_AaAa		==		0N
	A_AaAa   ==      0N
	A_Aa0a        ==      0N
	A_AaAaAa==  0N
	A_AaAaAa   == 0